// Auto-generated by auto-export-all-components script
// 组件导出（支持按需导入和树摇）

export { default as Monaco } from './components/Monaco/index.vue';
export { default as MonacoWithInstall } from './components/Monaco/install';
