// Auto-generated by auto-export-all-components script
import type { App, Plugin } from 'vue';

// 组件导入
import Monaco from './components/Monaco/index.vue';

// 全量导出（保持向后兼容）
export * from './components';
export * from './hooks';

// 全局插件
const VueElementPlusXShikiMonaco: Plugin = {
  install(app: App) {
    app.component('Monaco', Monaco);
  },
};

export { VueElementPlusXShikiMonaco };
export default VueElementPlusXShikiMonaco;
